#ifndef __DEFINE_HEADER__
#define __DEFINE_HEADER__

#include "iodefine.h"

#define DEBUG_LED_1	PORTE.PODR.BIT.B2
#define DEBUG_LED_2	PORTE.PODR.BIT.B4
#define DEBUG_LED_3	PORTE.PODR.BIT.B5

#define LED_1		PORT5.PODR.BIT.B4
#define LED_2		PORT5.PODR.BIT.B5

#define LED_7SEG_1	PORT1.PODR.BIT.B4
#define LED_7SEG_2	PORT1.PODR.BIT.B5
#define LED_7SEG_3	PORT1.PODR.BIT.B6
#define LED_7SEG_4	PORT1.PODR.BIT.B7
#define LED_7SEG_5	PORT2.PODR.BIT.B7
#define LED_7SEG_6	PORT3.PODR.BIT.B1
#define LED_7SEG_7	PORT3.PODR.BIT.B2

#define LF_SEN_LED	PORTH.PODR.BIT.B0
#define LS_SEN_LED	PORTH.PODR.BIT.B1
#define RF_SEN_LED	PORTH.PODR.BIT.B2
#define RS_SEN_LED	PORTH.PODR.BIT.B3

#define ENC_PULSE_COUNT_L	MTU1.TCNT
#define ENC_PULSE_COUNT_R	MTU2.TCNT

#define	MOT_DUTY_L	MTU4.TGRA
#define	MOT_DUTY_R	MTU4.TGRC

#define MOT_R_IN1	PORTB.PODR.BIT.B0
#define MOT_R_IN2	PORTB.PODR.BIT.B1
#define MOT_L_IN1	PORTB.PODR.BIT.B5
#define MOT_L_IN2	PORTB.PODR.BIT.B6
#define MOT_STBY	PORTB.PODR.BIT.B7

#define LOSIDE_BATTERY_R	2.70
#define HISIDE_BATTERY_R	10.0

#define CHIP_LED_ON	0
#define CHIP_LED_OFF	1

#define SEN_LED_ON		1
#define SEN_LED_OFF		0

#endif
